spring.application.name=medvault
server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://medvault-cloud-db-saiganeshmanyam18-2fbf.a.aivencloud.com:15483/defaultdb?ssl-mode=REQUIRED&allowPublicKeyRetrieval=true&useSSL=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_JMeGtsCTKgdz3Nrnvyg}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true